# --- VIVADO PROGRAMMING SCRIPT (Transcribed from Image 2) ---

open_hw_manager
connect_hw_server
open_hw_target

# Get first connected FPGA device
set device [lindex [get_hw_devices] 0]
current_hw_device $device
refresh_hw_device -update_hw_probes false $device

# --- Set bitstream file and program ---
# Targeting the bitfile generated by synth.tcl
set_property PROGRAM.FILE "top_fpga.bit" $device
program_hw_devices $device

# Finish and close
close_hw_manager